'use client';

import { useState } from 'react';
import { 
  BrainCircuit, CheckCircle2, Clock, XCircle, FileEdit,
  Sparkles, Check, X, Footprints, Utensils
} from 'lucide-react';
import styles from './approvals.module.css';

// Mock AI Suggestions from backend
const MOCK_AI_SUGGESTIONS = [
  {
    id: 'ai_1',
    patientName: 'Priya Sharma',
    patientId: 'PT-10492',
    avatar: 'https://i.pravatar.cc/150?u=priya',
    type: 'nutrition',
    icon: Utensils,
    suggestion: 'Prepare Poondu Kuzhambu for lunch',
    rationale: 'Based on the patient\'s recent lactation issues and mild anemia, Poondu (Garlic) Kuzhambu is a traditional Tamil remedy known to boost milk supply and immunity.',
    time: '12:30',
    duration: '45min',
    status: 'pending'
  },
  {
    id: 'ai_2',
    patientName: 'Meera Krishnan',
    patientId: 'PT-10495',
    avatar: 'https://i.pravatar.cc/150?u=meera',
    type: 'action',
    icon: Footprints,
    suggestion: 'Evening terrace walk together',
    rationale: 'Patient reported high stress levels yesterday. A 20-minute slow walk on the terrace provides Vitamin D synthesis and emotional grounding during the 3rd trimester.',
    time: '18:00',
    duration: '20min',
    status: 'pending'
  }
];

export default function AIApprovalsPage() {
  const [suggestions, setSuggestions] = useState(MOCK_AI_SUGGESTIONS);

  const handleApprove = (id) => {
    setSuggestions(suggestions.filter(s => s.id !== id));
    // Here we would push the approved (and potentially edited) task to the caretaker timeline via backend
    alert('Approved! Task sent to caretaker timeline.');
  };

  const handleReject = (id) => {
    setSuggestions(suggestions.filter(s => s.id !== id));
  };

  return (
    <div className="section">
      <div className={styles.header}>
        <div className={styles.headerTitle}>
          <BrainCircuit size={28} className={styles.headerIcon} />
          <h1>AI Approvals</h1>
        </div>
        <p className={styles.subtitle}>Review, edit, and approve care tasks generated by the Ollama Localized AI Engine.</p>
      </div>

      <div className={styles.statsRow}>
        <div className={styles.statCard}>
          <div className={`${styles.statIcon} ${styles.warning}`}>
            <Clock size={24} />
          </div>
          <div className={styles.statInfo}>
            <h3>{suggestions.length}</h3>
            <p>Pending Review</p>
          </div>
        </div>
        <div className={styles.statCard}>
          <div className={`${styles.statIcon} ${styles.primary}`}>
            <CheckCircle2 size={24} />
          </div>
          <div className={styles.statInfo}>
            <h3>14</h3>
            <p>Approved Today</p>
          </div>
        </div>
        <div className={styles.statCard}>
          <div className={`${styles.statIcon} ${styles.accent}`}>
            <BrainCircuit size={24} />
          </div>
          <div className={styles.statInfo}>
            <h3>Ollama</h3>
            <p>Engine Active</p>
          </div>
        </div>
      </div>

      <div className={styles.approvalsGrid}>
        {suggestions.map((item) => {
          const IconComponent = item.icon;
          return (
            <div key={item.id} className={styles.approvalCard}>
              <div className={styles.cardHeader}>
                <div className={styles.patientInfo}>
                  <img src={item.avatar} alt={item.patientName} className={styles.patientAvatar} />
                  <div className={styles.patientDetails}>
                    <h4>{item.patientName}</h4>
                    <span>{item.patientId}</span>
                  </div>
                </div>
                <div className={styles.aiBadge}>
                  <Sparkles size={12} fill="currentColor" /> AI Suggested
                </div>
              </div>

              <div className={styles.cardBody}>
                <div className={styles.aiRationale}>
                  "{item.rationale}"
                </div>

                <div className={styles.editorGroup}>
                  <span className={styles.editorLabel}>Task Description</span>
                  <textarea 
                    className={styles.editorTextarea} 
                    defaultValue={item.suggestion}
                  />
                </div>

                <div className={styles.timeRow}>
                  <div className={styles.editorGroup}>
                    <span className={styles.editorLabel}>Scheduled Time</span>
                    <input 
                      type="time" 
                      className={styles.editorInput} 
                      defaultValue={item.time} 
                    />
                  </div>
                  <div className={styles.editorGroup}>
                    <span className={styles.editorLabel}>Est. Duration</span>
                    <input 
                      type="text" 
                      className={styles.editorInput} 
                      defaultValue={item.duration} 
                    />
                  </div>
                </div>
              </div>

              <div className={styles.cardFooter}>
                <button className={styles.rejectBtn} onClick={() => handleReject(item.id)}>
                  <X size={18} /> Reject
                </button>
                <button className={styles.approveBtn} onClick={() => handleApprove(item.id)}>
                  <Check size={18} /> Approve to Care Plan
                </button>
              </div>
            </div>
          );
        })}
        {suggestions.length === 0 && (
          <div style={{ padding: '3rem', textAlign: 'center', color: 'var(--color-text-muted)', gridColumn: '1 / -1' }}>
            <CheckCircle2 size={48} style={{ opacity: 0.5, margin: '0 auto 1rem' }} />
            <h3>All Caught Up!</h3>
            <p>No pending AI suggestions require your approval.</p>
          </div>
        )}
      </div>
    </div>
  );
}
